### ISSUE TITLE
Trouble running mathjax node on multiple files

### ISSUE THREAD

**Issue by ssylvan** [mathjax/MathJax-node#149]
I tried a ton of stuff, and ended up with strange errors. This is the latest attempt where I try Very Hard to make sure no mathjax code runs interleaved (although ideally you'd want to use the async version of glob, and file io stuff for perf reasons), but it still isn't quite working. Note: not saying there's a matjax bug here, just that it might be nice to have an example of running this on multiple files at once since the startup time on Node is significant, so if you want to use this in conjunction with static site generators you really need to just do all files within Node. 

Code: https://gist.github.com/ssylvan/e7b4f18d435150216cce

**Comment by pkra** [comment]
Thanks for re-posting here. I'm afraid I don't have any issues with your code; it runs as expected using folder with a couple of test files. Can you be more specific as to what problems you're running into?

**Comment by ssylvan** [comment]
Bah, I can no longer reproduce it either. Wish I had written down the errors at least. Sigh. 

So, while this manually serialized version seems to work now, I gather it's supposed to work even if I run multiple mathjax operations at the same time? 'Cause that's what I orignally tried so I can try to reproduce the original error instead.

**Comment by ssylvan** [comment]
Ok. Here's the error I get when I try to read the files asynchronously. 
C:\Users\Sebastian\OneDrive\Documents\Blog\tools\lib\mj-page.js:528
  SVG.defaultEx = data.ex;
                ^

TypeError: Cannot set property 'defaultEx' of undefined
    at ConfigureTypeset (C:\Users\Sebastian\OneDrive\Documents\Blog\tools\lib\mj-page.js:528:17)
    at StartQueue (C:\Users\Sebastian\OneDrive\Documents\Blog\tools\lib\mj-page.js:491:3)
    at Function.CALLBACK.execute (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:236:26)
    at cb (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:218:59)
    at BASE.Object.Subclass.Process (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:488:38)
    at BASE.Object.Subclass.call (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:501:37)
    at Function.WAITEXECUTE (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:341:50)
    at cb (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:218:59)
    at BASE.Object.Subclass.Process (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:488:38)
    at BASE.Object.Subclass.call (file:///C:/Users/Sebastian/OneDrive/Documents/Blog/node_modules/MathJax/unpacked/MathJax.js:501:37)

Here's the code: https://gist.github.com/ssylvan/8b19fb016983a1ae38b7

**Comment by pkra** [comment]
> I gather it's supposed to work even if I run multiple mathjax operations at the same time? 

Sure. (Though I don't know what you have in mind with "at the same time".)

> This happens after quite a lot of files. 

Sounds like a memory leak. Can you give a rough idea on how many files? I tried it with ~100 files and didn't have an issue on my local machine.

**Comment by ssylvan** [comment]
Oh I only used maybe 50, the vast majority of which don't even have any MathJax code in them. Basically all the index.html files at sebastiansylvan.com (sans the mathjax js).

**Comment by pkra** [comment]
Closing this for now. Let us know if you have an update that might help reproduce the issue.
