### ISSUE TITLE
bug when switching data options

### ISSUE THREAD

**Issue by episodeyang** [mathjax/MathJax-node#28]
This bug does not appear when only one rendering opption is used. It happens only when we turn off the imgSVG or the imgPNG option. 

suppose we set:
```
data.imgSVG = true
```
then render. Everything renders fine.

Then if we switch to 
```
data.imgSVG = false
```
The resetGlyph method  gives an error message:
```
file:///Users/project/node_modules/MathJax-node/mathjax/unpacked/jax/output/SVG/jax.js?rev=2.4-beta-2:388
          GLYPH.defs.innerHTML = "";
                               ^
TypeError: Cannot set property 'innerHTML' of null
    at SVG.Augment.resetGlyphs (file:///Users/project/node_modules/MathJax-node/mathjax/unpacked/jax/output/SVG/jax.js?rev=2.4-beta-2:388:32)
    at StartQueue (/Users/projects/node_modules/MathJax-node/lib/mj-page.js:654:7)
    at Object.exports.typeset (/Users/project/node_modules/MathJax-node/lib/mj-page.js:709:35)
    at /Users/projects/server/mailer/mailerCtrl.js:201:38
    at fn (/Users/project/node_modules/async/lib/async.js:641:34)
    at Object._onImmediate (/Users/project/node_modules/async/lib/async.js:557:34)
    at processImmediate [as _immediateCallback] (timers.js:330:15)
```

This bug is relatively easy to understand. Might come back to this later.

**Comment by pkra** [comment]
This fell through the cracks. @episodeyang do you still have this problem? (And maybe a minimal example to reproduce this?)

**Comment by pkra** [comment]
Closing as abandoned. Might be related to https://github.com/mathjax/MathJax-node/issues/36.
