### ISSUE TITLE
Sanitize (combined) MathJax configurations

### ISSUE THREAD

**Issue by pkra** [mathjax/MathJax-node#330]
Originally reported at https://github.com/pkra/mathjax-node-page/issues/42.

(Combined) configurations cause problems; we should sanitize them as they are not needed anyway.

Minimal example

```
var mj = require("mathjax-node");
mj.config({
    MathJax: {
        config: ["TeX-AMS_SVG.js"]
    }
});
mj.typeset({
  math: 'E = mc^2',
  format: "TeX",
  svg:true,
}, function (data) {
  if (!data.errors) {console.log(data.svg)}

});
```

Results in

```
Error: TypeError: Cannot set property 'defaultEx' of undefined
    at StartQueue (/app/available_modules/1493815882000/mathjax-node/lib/main.js:677:35)
    at Function.execute (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Process (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at call (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Process (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at call (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Process (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at call (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Process (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at call (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Function.WAITEXECUTE (file:///app/available_modules/1493815882000/mathjax-node/node_modules/mathjax/unpacked/MathJax.js:348:50)
``

**Comment by pkra** [comment]
Fixed in develop.
