### ISSUE TITLE
Error: TypeError: speech.processExpression is not a function

### ISSUE THREAD

**Issue by sarike** [mathjax/MathJax-node#364]
I am using Mathjax in gitbook with the mathjax plugin.

When I run `gitbook pdf` to export pdf file. An error occured as follows:

```
Error: TypeError: speech.processExpression is not a function
    at GetSpeech (/srv/gitbook/node_modules/mathjax-node/lib/mj-single.js:540:29)
    at Function.execute (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:243:26)
    at cb (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Process (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at call (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:348:50)
    at cb (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:225:59)
    at Process (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:495:38)
    at call (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:508:37)
    at Function.WAITEXECUTE (file:///srv/gitbook/node_modules/mathjax/unpacked/MathJax.js:348:50)
```

**Comment by pkra** [comment]
Please provide a minimal example using mathjax-node that exhibits the problem.

**Comment by dpvc** [comment]
The speech-rule-engine changed its API several years ago (see [this commit](https://github.com/mathjax/MathJax-node/commit/db256eeae2749fe7db160b6f9845feb9d286aee1)), and since the `package.json` file had `*` as the SRE version, I bet the OP has an older version of `mathjax-node` and a newer version of `sre`, and they aren't using the same API.  Updating `mathjax-node` to the commit above should resolve the issue (but, of course, since SRE was removed in later versions, updating too far could cause the loss of the speech generation, and the changing of `mj-single.js` to `main.js`, along with the other API changes).

**Comment by pkra** [comment]
Ah, good guess. gitbook development seems a bit stalled (in private beta).

We should lock down the SRE version, I suppose.

**Comment by kachkaev** [comment]
@pkra how did you manage to lock `mathjax-node`? Is there any place in `book.json` where you can freeze the dependency version?

**Comment by pkra** [comment]
> @pkra how did you manage to lock mathjax-node? 

I don' think we ever did anything. SRE is no longer integrated into mathjax-node directly (but there's mathjax-node-sre).

> Is there any place in book.json where you can freeze the dependency version?

I haven't looked at gitbook in a long time. Googling brought me to recent discussions and [your fork](https://github.com/kachkaev/plugin-mathjax). I suppose i would not recommend using such old versions of mathjax-node and SRE (especially for performance reasons but also features and quality). However, it looks like the original plugin is not maintained much, so I have no idea what a good suggestion would be. 

If you want to update mathjax-node and maybe use mathjax-node-sre in your fork, feel free to ping me on the issue tracker

**Comment by kachkaev** [comment]
FYI: I have deleted https://github.com/kachkaev/plugin-mathjax, so if you are using my patch, please update to https://github.com/OrgVue/gitbook-plugin-mathjax. Also see https://github.com/GitbookIO/gitbook/issues/1875#issuecomment-399517404 for context.
